KestrelComputer/kestrel

- 3/src/mlm/bios.i
- 3/src/mlm/code.asm
- 3/src/mlm/rodata.asm
> Mlm character based

- 3/src/mlm/code.asm
> Implement command to write a byte to memory.

- 3/src/a/a.py
from: specifies the source to assemble.
to: defaults to "a.out" if unspecified; otherwise sets output filename.  Useful
for redo.
quiet: A flag; if present, silences non-error output.
> Add command-line option handling.

- 3/src/e/processor.c
- 3/src/mf/asm.fs
- 3/src/mf/lgp.fs
- 3/src/mf/mf.fs
- 3/src/mf/pass1.fs
- 3/src/mf/prolog-epilog.fs
- 3/src/mf/regs.fs
- 3/src/mf/syms.fs
- 3/src/ngaro/ngaro.asm.m4
This is the first and currently most viable Machine Forth-like language and compiler for the RISC-V architecture.  It's still a work-in-progress, but it's complete enough to actually write silly examples and actually have them work!
> Merge experimental Machine-Forth-like language.

- _layouts/default.html
- css/site.css
- index.html
Amazing what a little CSS rework can do; HTML modifications were quite minimal.
> Modernize the web presence a little bit.

- 3/src/stsv1/stsv1.bs
Right now, it's hardwired to ignore all commands given to it, on the basis that there's simply no filesystem implementation yet.
> Provide skeleton shell for STS.

- 3/src/bspl/bspl.fs
- 3/src/bspl/examples/hello.bs
> Make static records addressible in colon defs

- 3/src/bspl/bspl.fm/pass1.fs
- 3/src/bspl/examples/hello.bs
> Static record constructors

- 3/src/bspl/bspl.fm/pass1.fs
> Fix static string corruption.

- 3/src/stsv1/stsv1.bs
> Open and close files from ROM-disk.

- 3/src/stsv1/stsv1.bs
> Read rom files

- 3/src/stsv1/stsv1.bs
> Load program from storage

- 3/src/stsv1/stsv1.bs
> Initial ROM-disk creation.

- 3/src/stsv1/stsv1.bs
> Answer span of a segment, suitable for findtag.

- 3/src/stsv1/stsv1.bs
> Remove unused romtag code.

- 3/src/stsv1/hello.asm
- 3/src/stsv1/stsapi.inc
- 3/src/stsv1/stsv1.bs
> First demonstrated use of STS system call vtable.

- 3/src/stsv1/doc/abi.md
> Document program/STS interface standard.

- 3/bin/e.do
- 3/src/e/config.h
- 3/src/e/e.c
- 3/src/e/processor.c
- 3/src/e/processor.h
- 3/src/e/timeline.c
- 3/src/e/timeline.h
- 3/src/stsv1/doc/abi.md
> MGIA emulation (640x480)

- 3/src/stsv1/stsv1.bs
This is needed to properly process Milestone-2 data files.
Fixes #172
> Seek support.

- 3/src/e/e.c
- 3/src/stsv1/fbtest.asm
- 3/src/stsv1/m2.asm
- 3/src/stsv1/math.asm
- 3/src/stsv1/stsv1.bs
- 3/src/stsv1/stsv1.rom.asm
Steps towards #119 and #175.  Sorry for compound commits and merges, but work was done while on an airplane and no access to github to open separate issues in real-time.
> Milestone 2 foundations and framebuffer tester code

- 3/src/e/processor.c
> Fix how IRQ handler address is calculated.

- 3/src/e/address_space.c
- 3/src/e/config.h
- 3/src/e/processor.c
> Support external interrupts as well as traps.

- 3/src/e/address_space.c
- 3/src/e/address_space.h
> Finally found the LBU bug

- 3/src/bios/bios.asc.asm
- 3/src/bios/bios.asm
- 3/src/bios/bios.chr.asm
- 3/src/bios/bios.kia2.asm
> I believe this completes ASCII support in BIOS.

- 3/src/e/e.c
This might also make MacOS version run acceptably too!
> Speed up emulator significantly.

- 3/src/forth/assembler.fs
- 3/src/forth/compiler.fs
- 3/src/forth/dictionary.fs
- 3/src/forth/eforth.fs
- 3/src/forth/forth.fs
- 3/src/forth/kernel.fs
- 3/src/forth/vibe-2.2.fs
This has been a long time coming.
> Let the port of EForth V1.0 to Kestrel Forth V1.0 begin!

- 3/src/forth/compiler.fs
- 3/src/forth/eforth.fs
- 3/src/forth/k-sdl.fs
- 3/src/forth/v-mgia.fs
`?rx` and `!tx` are now complete.  I will need to call it a day for today; but, I think my next step are to focus on getting an interactive outer interpreter working, as that's the next chapter in the eForth guide.
> Complete console I/O drivers.

- 3/src/forth/compiler.fs
- 3/src/forth/dictionary.fs
- 3/src/forth/eforth.fs
- 3/src/forth/k-sdl.fs
- 3/src/forth/run
- 3/src/forth/v-mgia.fs
No interpreter implemented yet; however, you can now mash keys on the keyboard, and it does stuff w/out crashing!
Also, `find` now works properly, if 8x slower than it could potentially run.
> Line level console I/O and target-side dictionary search

- 3/all.do
- 3/roms/forth.do
- 3/roms/sdb.do
- 3/src/e/address_space.c
- 3/src/e/address_space.h
- 3/src/e/config.h
- 3/src/e/options.c
- 3/src/e/options.h
- 3/src/forth/sdcard.fs
- 3/src/sdb/README.md
- 3/src/sdb/kestrel3.fs
- 3/src/sdb/sdb.fs
> SDB support in emulator

- 3/src/a/a.py
- 3/src/bios/bios.asm
- 3/src/e/config.h
- 3/src/e/processor.c
- 3/src/forth/blockIO.fs
- 3/src/mlm/cpu/csrs.i
- 3/src/mlm/mlm.asm
- 3/src/ngaro/cpu/csrs.i
- 3/src/ngaro/mlm.asm
- 3/src/ngaro/ngaro.asm
- 3/src/stsv1/bios.asm
- 3/src/stsv1/bios.inc.asm
- 3/src/stsv1/bspl-abi/csrs.i
> Update emulator and software it runs to conform with Privileged ISA Spec 1.9

- index.html
Feel free to adapt this patch per your taste.
> index.html: Mention the other Kestrel blog, at hackaday.io

- _posts/2018-01-29-on-elf.md
- index.html
I've been meaning to get this off my chest for a looooooooooooooooooooooooooooooooong time.
> On ELF, Part 1
